#!/usr/bin/bash

bars=( 0 1 2 )
full_eww="$HOME/.local/bin/eww"

function kill-bar() {
  [[ `$full_eww state` ]] && pkill eww &>>/tmp/eww.log
}

function start-bar() {
  [[ `$full_eww state` ]] || $full_eww daemon &>>/tmp/eww.log

  printf '%s\n' ${bars[@]} | xargs -I % $full_eww open deftbar_m% &>>/tmp/eww.log
}


function restart-bar() {
  kill-bar &>>/tmp/eww.log
  start-bar &>>/tmp/eww.log
}

restart-bar
