#!/usr/bin/bash

full_eww="$HOME/.local/bin/eww"

function kill-bar() {
  [[ `$full_eww state` ]] && pkill eww &>>/tmp/eww.log
}

function start-bar() {
  [[ `$full_eww state` ]] || $full_eww daemon &>>/tmp/eww.log

  printf '%s\n' {0,1,2} | xargs -I % $full_eww open briskbar_m% &>>/tmp/eww.log
}


function restart-bar() {
  kill-bar &>>/tmp/eww.log
  start-bar &>>/tmp/eww.log
}

restart-bar